export {default as HomeLayout} from "./HomeLayout"
export {default as Home} from "./home/Home"
export {default as Artists} from "./artists/Artists"
export {default as ErrorPage} from "./ErrorPage"
export {default as SingleArtist} from "./singleArtist/SingleArtist"